name: decimal
version: 0.3.5
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: >
  The decimal package allows you to deal with decimal numbers without loosing
  precision.
homepage: https://github.com/a14n/dart-decimal
environment:
  sdk: '>=2.0.0-dev.66.0 <3.0.0'
dependencies:
  rational: # 0.3.8 - DONE: Secure code reviewed 44f3251
    git:
      url: git://github.com/KomodoPlatform/dart-rational.git
      ref: 44f3251dca11df633d1a392f5c93ea1c0b68bd37
dev_dependencies:
  test: ^1.2.0
